server:
  port: 8080
keycloak:
  enabled: true
  realm: primereact-app
  auth-server-url: http://192.168.1.101:8080/auth
  ssl-required: none
  resource: springboot-rest-api
  bearer-only: true
  confidential-port: 0
  use-resource-role-mappings: false
  principal-attribute: preferred_username
  cors: true
  security-constraints:
    - auth-roles:
      - User
      security-collections:
      - name: unsecured
        patterns:
        - /v1/users
    - auth-roles: 
      - Admin
      security-collections:
      - name: secured
        patterns:
        - /v1/admin
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-docs

    